language: java
jdk:
  - oraclejdk8

env:
  - OPENMRS_VERSION=1.9
  - OPENMRS_VERSION=1.12

sudo: required

services:
  - docker

before_install:
  - sudo chmod +x ./config_services.sh
  - ./config_services.sh

install: true

script:
  - sudo chmod +x ./run_build.sh
  - travis_wait 30 ./run_build.sh

cache:
  directories:
    - $HOME/.m2